public class Constant {
    public static final String NOT_AVAILABLE='N/a';
    public static final String FREE='Free';
    public static final String BAD_REQUEST='BAD_REQUEST';
    public static final String INVALID_UUID='UUID is not a valid Id';
    public static final String NOT_FOUND='NOT_FOUND';
    public static final String CONTACT_NOT_FOUND='Contact Record not found';
    public static final String PRODUCT_COUNTRY_MISSING='Product or Home Country not populated on Contact';
    public static final String PRODUCT_NOT_FOUND='Product Information not found';
    public static final String PERCENT_SYMBOL='%';
    
    public static final Integer STATUS_CODE_400=400;
    public static final Integer STATUS_CODE_404=404;
	public static final Integer STATUS_CODE_500=500;
	public static final Integer STATUS_CODE_200=200;
    
    public static final String EMAIL_ENCODING_UTF8='UTF-8';
    public static final String LANGUAGE_LOCALE_EN_US='en_US';
    public static final String TIMEZONE_LONDON='Europe/London';
    public static final String LOCALSIDKEY_EN_GB='en_GB';
    public static final String TYPE_ELECTRICAL='Electrical';
    public static final String REASON_FEEDBACK='Feedback';
    public static final String CURRENCYISOCODE_EUR='EUR';
    public static final String STATUS_NEW='New';
    public static final String ORIGIN_PHONE='Phone';
    public static final String URL_MAPPING_PRODUCT='services/apexrest/Product/';
    public static final String HTTP_METHOD_GET='GET';
    public static final String PROFILE_ADMIN='System Administrator';
    public static final String PROFILE_AGENT='Agent';
    public static final String USER_ALIAS='testUser';
    public static final String USER_EMAIL='testuser1198@gmail.com';
    public static final String USER_FIRST_NAME='Test';
    public static final String USER_LAST_NAME='User';
    public static final String PRODUCT_NAME='Test Product';
    public static final String COUNTRY_CODE_DE='DE';
    public static final String COUNTRY_NAME_GERMANY='Germany';
    public static final String ACCOUNT_NAME='Test Account';
    public static final String CONTACT_FIRSTNAME='Test';
    public static final String CONTACT_LASTNAME='Contact1';
    public static final String UUID='1234';
    public static final String CONTACT_EMAIL='testcontact11567@gmail.com';
    public static final String WRAPPER_VARIABLE_MESSAGE='message';
    public static final String WRAPPER_VARIABLE_PRODUCT_NAME='productName';
    public static final String WRAPPER_VARIABLE_COUNTRY='homeCountry';
    
    public static final Decimal COST_PER_CALENDAR_MONTH=29.50;
    public static final Decimal CARD_REPLACEMENT_COST=10;
    public static final Decimal NUMBER_WITH_DECIMAL=12.24;
    public static final Decimal NUMBER_WITHOUT_DECIMAL=12;
    public static final String FORMATTED_CURRENCY_WITH_DECIMAL='€ 12,24';
    public static final String FORMATTED_CURRENCY_WITHOUT_DECIMAL='€ 12';
    public static final String EURO_SYMBOL='€';
    public static final String FORMATTED_PERCENT_VALUE='12.24%';
    
}